matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: linux
      sudo: required
      dist: precise
      python: "2.7"
language: python
before_install:
  - source .travis_install.sh
  - source .travis_ssh_setup.sh
install:
  - pip install -e .
  - pip install -r docs/requirements.txt
before_script:
  - PWNLIB_NOTERM=1 python -c 'from pwn import *; print pwnlib.term.term_mode'
  - PWNLIB_NOTERM=1 python -c 'from pwn import *; print pwnlib.term.term_mode'
  - PWNLIB_NOTERM=1 python -c 'from pwn import *; print pwnlib.term.term_mode'
  - PWNLIB_NOTERM=1 python -c 'from pwn import *; print pwnlib.term.term_mode'
script: PWNLIB_NOTERM=1 make -C docs doctest

